Models/ErrorViewModel.cs
using System;

namespace ShubhamDhimanWebApp1.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/StudentData.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ShubhamDhimanWebApp1.Models
{
    public class StudentData
    {
        public int ID { get; set; }
        [Required]
        public int RollNumber { get; set; }
        [Required(ErrorMessage ="Please enter student name.")]
        public string Student_Name{get;set;}
        [Required]
        public string StudentEmail { get; set; }
        [Required(ErrorMessage ="Please enter course.")]
        public string Course { get; set; }
        [Required]
        public decimal Fees { get; set; }
    }
}

Controllers/StudentinfoController.cs
using Microsoft.AspNetCore.Mvc;
using ShubhamDhimanWebApp1.Data;
using ShubhamDhimanWebApp1.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ShubhamDhimanWebApp1.Controllers
{
    public class StudentinfoController : Controller
    {

        StudentDataContext studentDataContext;

        public StudentinfoController(StudentDataContext studentContext)
        {
            studentDataContext = studentContext;
        }
        public IActionResult GetAllData()
        {
            var Stud = studentDataContext.StudentsData.ToList();
            return View(Stud);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddnewStudent(StudentData Student)
        {
            var allready = studentDataContext.StudentsData.SingleOrDefault(all => all.RollNumber==Student.RollNumber);
            if (allready != null)
            {
                string msg = "Rollnumber Allready Exixts.";
                ViewBag.message = msg;
            }
            else if (ModelState.IsValid)
            {
                studentDataContext.StudentsData.Add(Student);
                studentDataContext.SaveChanges();
                return RedirectToAction("GetAllData");
            }
                
            return View("Create");
        }
    
        [HttpGet]
        public IActionResult StudentDetail(int id)
        {
            var detail = studentDataContext.StudentsData.SingleOrDefault(d => d.ID == id);
            return View(detail);
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var Stud = studentDataContext.StudentsData.SingleOrDefault(Stu => Stu.ID == id);
            return View(Stud);
        }

        [HttpPost]
        public IActionResult EditStudent(StudentData Student)
        {
            if (ModelState.IsValid)
            {
                studentDataContext.StudentsData.Update(Student);
                studentDataContext.SaveChanges();
                return RedirectToAction("GetAllData");
            }
            return View("Edit");
        }
       
        public IActionResult DeleteStudentInfo(int id)
        {
            var Stud = studentDataContext.StudentsData.SingleOrDefault(Stu => Stu.ID == id);
            studentDataContext.StudentsData.Remove(Stud);
            studentDataContext.SaveChanges();
            return RedirectToAction("GetAllData");
        }
        
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ShubhamDhimanWebApp1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Studentinfo" asp-action="GetAllData">CoachingCenter</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Studentinfo" asp-action="GetAllData">GetAllStudents</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Coaching Center - <a asp-area="" asp-controller="Studentinfo" asp-action="GetAllData"></a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>



Views/Studentinfo/Create.cshtml
@model ShubhamDhimanWebApp1.Models.StudentData
@{
    ViewData["Title"] = "AddNewStudent";
}
<div class="container">
<div class="row">
    <div class="col-6 offset-3">
        <form asp-controller="Studentinfo" asp-action="AddNewStudent" method="post">
            <div class="form-group">
                <label asp-for="RollNumber"></label>
                <input type="number" asp-for="RollNumber" class="form-control" placeholder="Enter Student RollNumber"/>
                <span asp-validation-for="RollNumber" class="text-danger">@ViewBag.message</span>
            </div>
            <div class="form-group">
                <label asp-for="Student_Name"></label>
                <input type="text" asp-for="Student_Name" class="form-control" placeholder="Enter Student Name" />
                <span asp-validation-for="Student_Name" class="text-danger"></span>

            </div>
            <div class="form-group">
                <label asp-for="StudentEmail"></label>
                <input type="email" asp-for="StudentEmail" class="form-control" placeholder="Enter Student Email" />
                <span asp-validation-for="StudentEmail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Course"></label>
                <input type="text" asp-for="Course" class="form-control" placeholder="Enter Student Course" />
                <span asp-validation-for="Course" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Fees"></label>
                <input type="number" min="4500" max="20000" asp-for="Fees" class="form-control" placeholder="Enter Student Fees between 4000 to 20,000." />
                <span asp-validation-for="Fees" class="text-danger"></span>
            </div>

            <div class="text-center">
                <input type="submit" value="submit" class="btn btn-info btn-lg" />
            </div>
        </form>
    </div>
</div>
</div>

Views/Studentinfo/Edit.cshtml
@model ShubhamDhimanWebApp1.Models.StudentData
@{
}
<div class="row">
    <div class="col-6 offset-3">
        <form asp-controller="Studentinfo" asp-action="EditStudent" method="post">
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="RollNumber"></label>
                <input asp-for="RollNumber" class="form-control" placeholder="Enter Student RollNumber" readonly/>
            </div>
            <div class="form-group">
                <label asp-for="Student_Name"></label>
                <input type="text"  asp-for="Student_Name" class="form-control" placeholder="Enter Student Name" />
                <span asp-validation-for="Student_Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StudentEmail"></label>
                <input type="email" asp-for="StudentEmail" class="form-control" placeholder="Enter Student Email" />
                <span asp-validation-for="StudentEmail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Course"></label>
                <input type="text" asp-for="Course" class="form-control" placeholder="Enter Student Course" />
                <span asp-validation-for="Course" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Fees"></label>
                <input type="number" min="4000" max="20000" asp-for="Fees" class="form-control" placeholder="Enter Student Fees between 4000 to 20,000" />
                <span asp-validation-for="Fees" class="text-danger"></span>
            </div>

            <div class="text-center">
                <input type="submit" value="Update" class="btn btn-info btn-lg" onclick="return confirm('Are you sure yoy want to update this record ?')"/>
            </div>
        </form>
    </div>
</div>


Views/Studentinfo/GetAllData.cshtml
@model IEnumerable<ShubhamDhimanWebApp1.Models.StudentData>
@{
    ViewData["Title"] = "GetAllData";
}
<div class="container">
<div class="border mb-1 bg-info">
    <h2 style="color:darkred;text-align:center">StudentInformation</h2>
</div>
<div class="btn btn-outline-info mb-1">
    <a asp-controller="Studentinfo" asp-action="Create">Create New Student</a>
</div>
<table class="table table-striped bg-primary">
    <tr>
        <th>RollNumber</th>
        <th>Student_Name</th>
        <th>StudentEmail</th>
        <th>Course</th>
        <th>Fees</th>
        <th>Actions[Details/Edit/Delete]</th>
        
    </tr>
   @foreach (var Students in Model)
    {
    <tr class="text-white">
        <td>@Students.RollNumber</td>
        <td>@Students.Student_Name</td>
        <td>@Students.StudentEmail</td>
        <td>@Students.Course</td>
        <td>@Students.Fees</td>
        <td>
            <a asp-controller="Studentinfo" asp-action="StudentDetail" class="btn btn-success" asp-route-id="@Students.ID">Detail</a>

            <a asp-controller="Studentinfo" asp-action="Edit" class="btn btn-secondary" asp-route-id="@Students.ID"
               onclick="return confirm('Are you sure to edit record ?')">Edit</a>

            <a asp-controller="Studentinfo" asp-action="DeleteStudentInfo" class="btn btn-danger" asp-route-id="@Students.ID" onclick="return confirm('Are you sure to Delete this record?')">Delete</a>
        </td>
    </tr>
    }
</table>
<div class="bg-light">
    <marquee><b> Design and Developed By: Shubham Kumar </b></marquee>
</div>
</div>



Views/Studentinfo/StudentDetail.cshtml
@model ShubhamDhimanWebApp1.Models.StudentData
@{
    ViewBag.Title = "StudentDetail";
}

<div class="card">
    <div class="card-header text-primary text-lg-center">
        <h5>Student Detail</h5>
    </div>
    <div class="card-body bg-info">
        
        <table class="table">
            <tr>
                <th>RollNumber</th>
                <th>Student Name</th>
                <th>Student Email</th>
                <th>Course</th>
                <th>Fees</th>
            </tr>
            <tr class="text-white">
                <td>@Model.RollNumber</td>
                <td>@Model.Student_Name</td>
                <td>@Model.StudentEmail</td>
                <td>@Model.Course</td>
                <td>@Model.Fees</td>
            </tr>
        </table>
       
        <div class="card-footer bg-dark text-white font-weight-lighter">
            <h6>Vishu skill center</h6>
        </div>
    </div>
</div>
